---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: kafka-zookeeper-regional
provisioner: kubernetes.io/gce-pd
reclaimPolicy: Retain
allowVolumeExpansion: true
parameters:
  type: pd-standard
  replication-type: regional-pd
  zones: asia-southeast1-a, asia-southeast1-c, asia-southeast1-b